/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tarefa1;

public class App {
   

    public static void main(String[] args) {
       App aplicacao = new App();
       Pessoa pl = new Pessoa("Zezinho");
       Piloto pil = new Piloto("Huquinho");
       Carro car = new Carro("Kombi");
       Moto mot = new Moto("Vespa");
    }
}
